# Generated by Django 5.2.7 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Doctor profile image', null=True, upload_to='doctor_profiles/'),
        ),
    ]
